apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapp2
  namespace: opsforge-system
spec:
  ingressClassName: nginx
  rules:
    - host: testapp2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testapp2-frontend
                port:
                  number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: testapp2-backend
  namespace: opsforge-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testapp2-backend
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
